name: "moon"

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: -v start-dev --import-realm
    #command: export --file /opt/keycloak/data/import/test.json --realm moon
    volumes:
      - ./keycloak/themes/moon-theme/dist_keycloak:/opt/keycloak/providers/
      - ./keycloak/imports:/opt/keycloak/data/import
    depends_on:
      - keycloakdb
    ports:
      - '8081:8080'

  keycloakdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  moondb:
    image: postgres:16
    volumes:
      - postgres_data_moon:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: moon
      POSTGRES_USER: moon
      POSTGRES_PASSWORD: moon
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  postgres_data_moon:
